name: 'metanorma-site-generate'
description: 'Generate a Metanorma site from source documents with comprehensive configuration options'
author: 'actions-mn'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  source-path:
    description: 'Source path containing the configuration (manifest) file and documents'
    required: false
    default: '.'
  output-dir:
    description: 'Output directory for the generated site'
    required: false
    default: '_site'
  config-file:
    description: 'Metanorma configuration (manifest) file name'
    required: false
    default: 'metanorma.yml'
  agree-to-terms:
    description: 'Agree to all third-party licensing terms (WARNING: ensure you understand what you are agreeing to!)'
    required: false
    default: 'false'
  install-fonts:
    description: 'Install missing fonts automatically'
    required: false
    default: 'true'
  continue-without-fonts:
    description: 'Continue processing even when fonts are missing'
    required: false
    default: 'false'
  strict:
    description: 'Run metanorma in strict mode (fail on warnings)'
    required: false
    default: 'false'
  progress:
    description: 'Display progress-related logs during processing'
    required: false
    default: 'false'
  use-bundler:
    description: 'Use bundler to execute metanorma (required if installed via bundle)'
    required: false
    default: 'false'
  timestamps:
    description: 'Add timestamps to log output'
    required: false
    default: 'false'

outputs:
  site-path:
    description: 'Path to the generated site directory'
  config-used:
    description: 'Configuration file that was used'
  metanorma-version:
    description: 'Version of metanorma that was used'

runs:
  using: 'node24'
  main: 'dist/index.js'
