name: 'metanorma-site-generate'
description: 'Perform metanorma site generate'
inputs:
  source-path:
    description: Source path, usually directory where configuration
      (manifest) file is
    default: '.'
  output-dir:
    description: Output directory for the generated site
    default: _site
  config-file:
    description: 'Metanorma configuration (manifest) file'
    default: metanorma.yml
  agree-to-terms:
    description: 'Agree / Disagree with all third-party licensing terms
      presented (WARNING: do know what you are agreeing with!)'
    default: '' # false
  install-fonts:
    description: 'Install missing fonts'
    default: 'false'
  continue-without-fonts:
    description: 'Continue processing even when fonts are missing'
    default: '' # false
  strict:
    description: 'Run metanorma in strict mode'
    default: '' # false
  progress:
    description: 'Display progress related logs'
    default: 'false' # false
  use-bundler:
    description: 'Run in bundler'
    default: '' # false
  # stylesheet:
  #   description: 'Stylesheet file path for rendering HTML page'
  # template-dir:
  #   description: 'Liquid template directory to render site design'

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      verlte() {
        printf '%s\n' "$1" "$2" | sort -C -V
      }
      verlt() {
        ! verlte "$2" "$1"
      }

      METANORMA_VERSION=$(cd ${{ inputs.source-path }}; ${{ inputs.use-bundler == 'true' && 'bundle exec' || '' }} metanorma --version | head -1 | cut -d' ' -f2)
      METANORMA_LEGACY=$(verlt ${METANORMA_VERSION} 1.10.0 && echo "true" || echo "false")
      METANORMA_FLAGS=""

      if [ "${{ inputs.strict }}" == "true" ]; then
        METANORMA_FLAGS+="--strict"
      fi
      if [ "${{ inputs.progress }}" != "true" ]; then
        METANORMA_FLAGS+=" --no-progress"
      fi
      if [ "${{ inputs.agree-to-terms }}" == "true" ]; then
        METANORMA_FLAGS+=" --agree-to-terms"
      fi

      if [ "${{ inputs.install-fonts }}" != 'true' ]; then
        METANORMA_FLAGS+=" --no-install-fonts"
      elif [ "$METANORMA_LEGACY" == "true" ]; then
        METANORMA_FLAGS+=" --no-no-install-fonts"
      else
        METANORMA_FLAGS+=" --install-fonts"
      fi

      if [ "${{ inputs.continue-without-fonts }}" != 'true' ]; then
        METANORMA_FLAGS+=" --no-continue-without-fonts"
      elif [ "$METANORMA_LEGACY" == "true" ]; then
        METANORMA_FLAGS+=" --no-no-continue-without-fonts"
      else
        METANORMA_FLAGS+=" --continue-without-fonts"
      fi
      echo "METANORMA_FLAGS=${METANORMA_FLAGS}" >> $GITHUB_ENV

  - shell: bash
    run: |
      cd ${{ inputs.source-path }}
      ${{ inputs.use-bundler == 'true' && 'bundle exec' || '' }}       \
        metanorma site generate .                                      \
        -o ${{ inputs.output-dir }}                                    \
        -c ${{ inputs.config-file }}                                   \
        ${{ env.METANORMA_FLAGS }}
