name: Release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next version. Values: x.y.z, major, minor, patch. Defaults to patch.
        required: false
        default: 'patch'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: actions-mn/shared/.github/workflows/release.yml@main
    with:
      next_version: ${{ inputs.next_version }}
      create_release: true
